### ISSUE TITLE
"CUDA out of memory Error" on running evaluate.py

### ISSUE THREAD

**Issue by likewind1993** [YBIGTA/pytorch-hair-segmentation#28]
When about 30 images were processed,  "Cuda out of Memory error" happens.
It runs on a GTX 1080 with 8GB memory.
```
[ 29/210] processing image... 
[ 30/210] processing image... 
Traceback (most recent call last):
  File "E:/2018/final/HairSegment/pytorch-hair-segmentation/evaluate.py", line 94, in <module>
    logit = net(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\2018\final\HairSegment\pytorch-hair-segmentation\networks\pspnet.py", line 108, in forward
    p = self.psp(f)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\2018\final\HairSegment\pytorch-hair-segmentation\networks\pspnet.py", line 59, in forward
    return torch.cat(features, dim=1)
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 8.00 GiB total capacity; 5.75 GiB already allocated; 17.18 MiB free; 351.95 MiB cached)
```

**Comment by likewind1993** [comment]
The reason of this error is code blow. 
```
# log measurements
metric.update((logit, label))
```
it saved a lot temp vars in GPU memory,  so , if you have same problem, add the code blow can solve it.
```
# log measurements
metric.update((logit, label))
del logit
del label
#delete the temp vars after each loop, which can release the memory in GPU.
```

**Comment by Jooong** [comment]
@likewind1993 Thanks for sharing this issue. I applied torch.no_grad so that gradients are not computed. It saves memories a lot.
