### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by hhy018** [YBIGTA/pytorch-hair-segmentation#37]
请问模型是不是使用./models/pspnet_resnet101_sgd_lr_0.002_epoch_100_test_iou_0.918.pth默认的，
编译evaluate.py 
Traceback (most recent call last):
  File "G:/deeep/pytorch-hair-segmentation-master/pytorch-hair-segmentation-master/evaluate.py", line 51, in <module>
    state = torch.load(ckpt_dir)
  File "C:\Users\hhy\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\torch\serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\hhy\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\torch\serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by Bramichou** [comment]
I think you have to download models with `git-lfs`, because the models are weighty :)

**Comment by Jooong** [comment]
@Bramichou thanks for your comment. @hhy018 could you download models and retry? If you have the same problem after that, please reopen the issue.

**Comment by ybsave** [comment]
But how to " download models with git-lfs"? Any suggestions? Thank you.
